### ISSUE TITLE
(C.2.a.4): Unklarer Kommentar

### ISSUE THREAD

**Issue by ithieman** [johner-institut/it-security-guideline#10]
Bei C.2.a.4 ist Stufe 1 ausgewählt, aber im Kommentar „Bei unkritischen Produkten ist die Stufe 2 vertretbar“ angegeben. Hier ist unklar, was das Kommentar meint, da ja schon eine niedrigere Stufe ausgewählt ist.

**Comment by johner-institut** [comment]
Eine höhere Stufe bedeutet, dass die Umsetzung später erfolgen kann. Habe entsprechenden Hinweis ergänzt.
