### ISSUE TITLE
Line-Items ohne Stufenauswahl

### ISSUE THREAD

**Issue by ithieman** [johner-institut/it-security-guideline#11]
Folgende Line-Items habe derzeit keine Stufenauswahl, hier ist unklar, wie damit umgegangen werden soll. Wenn die Stufe unklar ist oder vom Hersteller selbst definiert werden sollte würde es helfen, wenn es dementsprechend vermerkt wäre (anstatt leer):
C.1.b.iv.2
C.1.c.11
C.1.c.12
C.1.f.2
C.1.f.5
C.1.f.8 
D.2.b.11

**Comment by johner-institut** [comment]
Absolut korrekt! Wir haben die Stufen inzwischen eingefügt. Danke!
