### ISSUE TITLE
C.1.a.6 sehr unklar und grammatikalisch falsch

### ISSUE THREAD

**Issue by giraone** [johner-institut/it-security-guideline#15]
In C.1.a.6 steht

> Der Hersteller hat die Risiken (Gefährdung) analysiert, die folgen, wenn die nicht die spezifizierten Benutzer in der spezifizierten Benutzungsumgebung mit dem System arbeiten 

Das Beispiel dazu ist:

> [^C1-03]: Beispiele: Der Betreiber hat keinen Virenschutz installiert. Benutzer teilen sich ein Passwort.

Der Satz ist grammatikalisch komplett falsch (".. die nicht die .."), aber es ist sehr unklar, was die Intention ist, da die Beispiele nicht passen. Ist gemeint:

1. Ein nicht-spezifierter Nutzer (also z.B. einer ohne eine Schulung, oder ein Gelegenheitstäter) arbeitet mit der Medizinproduktsoftware.
2. Ein spezifierter Nutzer arbeitet in einer nicht zur Spezifikation konformen Umgebung, also z.B. er arbeitet mit dem System in einer Umgebung ohne Virenscanner, obwohl der Betreiber spezifiert hat, dass ein Virenschutz genutzt werden soll. Ein anderes Beispiel wäre ein Benutzer arbeitet mit einem Web-Browser Z mit der Software, obwohl nur Web-Browser des Typs X und Y als Nutzungsumgebung vorgesehen sind. Hier passt also das Beispiel 1, aber das Beispiel 2 passt nicht, denn das Teilen von Passwörtern hat nichts mit der Benutzungsumgebung zu tun. Maximal mit mangelnder Schulung, aber mangelnde Schulung von Anwendern ist kein spezielles IT-Security-Problem.  

Bitte klarstellen und korrigieren.

**Comment by johner-institut** [comment]
Generell einverstanden. Änderungen sind übernommen. Nur den "Betreiber" durch "Hersteller" ersetzt, weil es die Aufgabe der Hersteller ist, diese Vorgaben zu machen.
