### ISSUE TITLE
Stufe 1 bei C.1.e.3 unklar 

### ISSUE THREAD

**Issue by giraone** [johner-institut/it-security-guideline#16]
Der Punkt C.1.e.3 "_Der Hersteller hat konkrete Prüfkriterien in seinen Vorgabedokumenten für die Code-Reviews._" hat die Stufe 1. Code-Reviews selbst sind in C.1.e.2 aber als Stufe 2 klassifiziert.

Entweder müssen es 4 Punkte getrennt nach
- Es gib **automatische** Prüfungen der Einhaltung der Coding-Guidelines
- Es gibt Code-Reviews durch **Personen**
und
- Es gibt eine Dokumentation der Kriterien der automatische Prüfungen
- Es gibt eine Dokumentation der Kriterien der manuellen Code-Reviews
sein oder der Punkt C.1.e.3 bezieht sich auf beides, also Code-Reviews **und** automatische Prüfungen, dann wäre die Stufe 1 korrekt (sollte dann im Text aber genannt werden), sonst nicht.

**Comment by johner-institut** [comment]
Absolut zutreffend! Danke für den Hinweis. Ändere ich sofort!
