### ISSUE TITLE
Password requirements - update to current NIST Digital Identity Guidelines 800-63B

### ISSUE THREAD

**Issue by gabeng** [johner-institut/it-security-guideline#2]
I would suggest to adopt the current NIST Digital Identity Guidelines (June 2017) regarding choice of password (D.2.a.3). They reflect current expert opinion.

> 5.1.1.1 Memorized Secret Authenticators
> Memorized secrets SHALL be at least 8 characters in length if chosen by the subscriber. Memorized secrets chosen randomly by the CSP or verifier SHALL be at least 6 characters in length and MAY be entirely numeric. If the CSP or verifier disallows a chosen memorized secret based on its appearance on a blacklist of compromised values, the subscriber SHALL be required to choose a different memorized secret. No other complexity requirements for memorized secrets SHOULD be imposed.

https://pages.nist.gov/800-63-3/sp800-63b.html#sec5

**Comment by johner-institut** [comment]
Exzellent advise: I'm just about updating the section corresponding section accordingly.
