### ISSUE TITLE
Fußnoten werden doppelt genutzt

### ISSUE THREAD

**Issue by stegelmannk** [johner-institut/it-security-guideline#3]
Die folgenden Fußnoten werden doppelt genutzt:
C2a-02
C2a-04
C2a-05
C2b-01
C3-01 

Sowohl in DE als auch in EN.
Die Zuodnung lässt sich erkennen, birgt jedoch die Möglichkeit der Verwirrung.

**Comment by johner-institut** [comment]
Absolut zutreffend! Wir haben die komplette Nummerierung überarbeitet. Danke für den Hinweis!
